const ACTION_TYPES = {
    COUNTER_ADD: 'COUNTER_ADD',
    COUNTER_SUB: 'COUNTER_SUB',
    COUNTER_SET_STEP: 'COUNTER_SET_STEP',
    SET_THEME: 'SET_THEME',
 
 // users
    CREATE_USER: 'CREATE_USER',
    READ_USER:   'READ_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',

// user info
    GET_USER_ACTION:  'GET_USER_ACTION',
    GET_USER_REQUEST: 'GET_USER_REQUEST',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_ERROR:   'GET_USER_ERROR'


};
export default ACTION_TYPES;