const ACTION_TYPES = {
    COUNTER_ADD: 'COUNTER_ADD',
    COUNTER_SUB: 'COUNTER_SUB',
    COUNTER_SET_STEP: 'COUNTER_SET_STEP',
    SET_THEME: 'SET_THEME',
    CREATE_USER: 'CREATE_USER',
    READ_USER:   'READ_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',

};
export default ACTION_TYPES;